### ISSUE TITLE
module 'DNS' has no attribute 'Type'

### ISSUE THREAD

**Issue by refayathaque** [cisagov/trustymail-lambda#3]
@jsf9k hi! I am trying to run trustymail in a Lambda function but keep running into the same issue over and over again. I am using the provided `lambda_handler.py` and I am getting the same error as when I tried using trustymail from the `lambda_functions` repository. Is there a solution to this problem? Can I be put in touch with folks that are being able to successfully run trustymail on their boxes so I understand how they are doing it? I would appreciate ANY help I get from you guys on this, I have been struggling for way too long :(

`START RequestId: fd3b5a22-82e1-4f05-8ef6-e419847b67a3 Version: $LATEST
2019-07-15 15:29:16,183 INFO AWS Event was: {'domain_name': 'dhs.gov'}
module 'DNS' has no attribute 'Type': AttributeError
Traceback (most recent call last):
  File "/var/task/lambda_handler.py", line 98, in handler
    from trustymail.trustymail import scan
  File "/var/task/trustymail/trustymail.py", line 11, in <module>
    import spf
  File "/var/task/spf.py", line 111, in <module>
    if not hasattr(DNS.Type, 'SPF'):
AttributeError: module 'DNS' has no attribute 'Type'`

Related to: https://github.com/cisagov/trustymail/issues/41

**Comment by mcdonnnj** [comment]
@refayathaque If you are still having trouble with this could you provide information regarding your environment and process for building the lambda?

**Comment by refayathaque** [comment]
Hi @mcdonnnj ,

So I never managed to resolve this issue, and I resorted to using an EC2 to build trustymail for Lambda. I've prepared a little guide on another ticket in the `trustymail repo`.

https://github.com/cisagov/lambda_functions/issues/45#issuecomment-519616095
